name: release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for NPM trusted publishing.
  contents: read

jobs:
  npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: npm test
      - run: npm stage publish
